### PR TITLE
Add Docker build scripts and Update README.md.

### PR DESCRIPTION
**Pull request by VAllens**
FYI.

### CODE REVIEW

**Comment by sundy-li** [comment]
Thanks

**Comment by sundy-li** [comment]
镜像有点大, 我修改了一下readme, 本地build image 然后运行

**Comment by VAllens** [comment]
Not at all. :)
It's fun to help open source projects !!!

**But the point 3**, advice to write more detailed commands.
Because someone may be puzzled...

#### Sample commands: ####
``` Shell
git clone https://github.com/sundy-li/wechat_brain.git
cd wechat_brain
docker build . -t wechat_brain
docker run -p 8998:8998 --name my_wechat_brain -d wechat_brain
```

**Comment by sundy-li** [comment]
ok

**Pull request merged**
